"""clases_7_8_9_10_full_integration

Revision ID: 16a12024870b
Revises: 8e38960f5130
Create Date: 2026-09-27 23:00:25.780494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a12024870b'
down_revision: Union[str, Sequence[str], None] = '8e38960f5130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_pedidos', schema=None) as batch_op:
        batch_op.alter_column('precio_unitario',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('imagen_url', sa.String(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('acepto_tratamiento', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('fecha_consentimiento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('fecha_baja', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.drop_column('fecha_baja')
        batch_op.drop_column('activo')
        batch_op.drop_column('fecha_consentimiento')
        batch_op.drop_column('acepto_tratamiento')
        batch_op.drop_column('hashed_password')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('imagen_url')
        batch_op.drop_column('imagen')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('item_pedidos', schema=None) as batch_op:
        batch_op.alter_column('precio_unitario',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
